<?php
namespace PPHP\tests\tools\patterns\buffer;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-31 at 18:34:58.
 */
class MapBufferTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tests\tools\patterns\buffer\TestBuffer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new TestBuffer();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\patterns\buffer\MapBuffer::getDate
   */
  public function testGetDate(){
    $this->assertEquals('testKey', $this->object->get('testKey'));
  }

  /**
   * @covers PPHP\tools\patterns\buffer\MapBuffer::__construct
   */
  public function test_construct(){
    $this->assertEquals(50, $this->object->getMaxSizeBuffer());
  }

  /**
   * @covers PPHP\tools\patterns\buffer\MapBuffer::setMaxSizeBuffer
   * @covers PPHP\tools\patterns\buffer\MapBuffer::getMaxSizeBuffer
   */
  public function testSetMaxSizeBuffer(){
    $this->object->setMaxSizeBuffer(20);
    $this->assertEquals(20, $this->object->getMaxSizeBuffer());
  }

  /**
   * @covers PPHP\tools\patterns\buffer\MapBuffer::getSizeBuffer
   */
  public function testGetSizeBufferForEmptyBuffer(){
    $this->assertEquals(0, $this->object->getSizeBuffer());
  }

  /**
   * @covers PPHP\tools\patterns\buffer\MapBuffer::getSizeBuffer
   */
  public function testGetSizeBufferForNonEmptyBuffer(){
    $this->object->get('testKey');
    $this->assertEquals(1, $this->object->getSizeBuffer());
  }

  /**
   * @covers PPHP\tools\patterns\buffer\MapBuffer::getDate
   */
  public function testGetDateForFullBuffer(){
    $this->object->setMaxSizeBuffer(2);
    $this->object->get('1');
    $this->object->get('2');
    $this->object->get('3');
    $this->assertEquals(2, $this->object->getSizeBuffer());
  }
}
