<?php
namespace PPHP\tests\tools\classes\standard\storage\database;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-23 at 17:27:32.
 */
class PDOTest extends \PHPUnit_Framework_TestCase{
  /**
   * Имя драйвера.
   */
  const dbDriver = 'mysql';
  /**
   * Адрес сервера с БД.
   */
  const host = 'localhost';
  /**
   * Имя БД.
   */
  const dbName = 'testingDB';
  /**
   * Пользователь БД.
   */
  const user = 'admin';
  /**
   * Пароль пользователя БД.
   */
  const password = 'admin';
  /**
   * @var \PPHP\tools\classes\standard\storage\database\PDO
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\standard\storage\database\PDO(self::dbDriver . ':host=' . self::host . ';dbname=' . self::dbName, self::user, self::password);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\storage\database\PDO::query
   */
  public function testQuery(){
    $this->setExpectedException('\PPHP\tools\classes\standard\storage\database\QueryException');
    $this->object->query('SELECT * FROM `1`');
  }
}
