<?php
namespace PPHP\tests\tools\classes\standard\fileSystem\io;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-02 at 14:22:36.
 */
class FileReaderTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\standard\fileSystem\io\FileReader
   */
  protected $object;

  /**
   * Имя тестируемого файла в текущем каталоге.
   */
  const testFileName = 'testFile.txt';
  /**
   * Дескриптор тестируемого файла.
   * @var resource
   */
  static $descriptor;

  public static function setUpBeforeClass(){
    fclose(fopen(self::testFileName, 'a+'));
    self::$descriptor = fopen(self::testFileName, 'r+');
    fwrite(self::$descriptor, 'First test line'.PHP_EOL.'Second test line'.PHP_EOL);
  }

  public static function tearDownAfterClass(){
    fclose(self::$descriptor);
    unlink(self::testFileName);
  }

  protected function setUp(){
    $this->object = new \PPHP\tools\classes\standard\fileSystem\io\FileReader(self::$descriptor);
    fseek(self::$descriptor, 0);
  }

  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::read
   */
  public function testRead(){
    $this->object->read();
    $this->assertEquals('i', $this->object->read());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::read
   */
  public function testReadForEndFile(){
    $length = 31 + 2 * strlen(PHP_EOL);
    for($i = $length; $i--;){
      $this->object->read();
    }
    $this->assertFalse($this->object->read());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::readLine
   */
  public function testReadLine(){
    $this->object->read();
    $this->assertEquals('irst test line', $this->object->readLine());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::readLine
   */
  public function testReadLineForEndFile(){
    $length = 31 + 2 * strlen(PHP_EOL);
    for($i = $length; $i--;){
      $this->object->read();
    }
    $this->assertFalse($this->object->readLine());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::readSet
   */
  public function testReadSet(){
    $this->object->read();
    $this->assertEquals('irst ', $this->object->readSet(5));
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::readAll
   */
  public function testReadAll(){
    $this->object->read();
    $this->assertEquals('irst test line'.PHP_EOL.'Second test line'.PHP_EOL, $this->object->readAll());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileReader::readSet
   */
  public function testReadSetForEndFile(){
    $length = 31 + 2 * strlen(PHP_EOL);
    for($i = $length; $i--;){
      $this->object->read();
    }
    $this->assertEquals('', $this->object->readSet(5));
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileSeekIO::setPosition
   */
  public function testSetPosition(){
    $this->assertTrue($this->object->setPosition(1));
    $this->assertEquals('i', $this->object->read());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileSeekIO::getPosition
   */
  public function testGetPosition(){
    $this->object->read();
    $this->assertEquals(1, $this->object->getPosition());
  }

  /**
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileClosed::close
   * @covers PPHP\tools\classes\standard\fileSystem\io\FileClosed::isClose
   */
  public function testClose(){
    $this->assertFalse($this->object->isClose());
    $this->assertTrue($this->object->close());
    $this->assertTrue($this->object->isClose());
  }
}
