<?php
namespace PPHP\tests\tools\classes\special\storage\relationTable;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-16 at 07:18:54.
 */
class PointerTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\special\storage\relationTable\Pointer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\Pointer(5, 5);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Pointer::setLine
   */
  public function testSetLine(){
    $this->object->setLine(1);
    $this->assertEquals(5, $this->object->getPosition());
    $this->object->setLine(3);
    $this->assertEquals(15, $this->object->getPosition());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Pointer::getPosition
   */
  public function testGetPosition(){
    $this->assertEquals(5, $this->object->getPosition());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Pointer::nextPosition
   */
  public function testNextPosition(){
    $this->object->nextPosition();
    $this->assertEquals(10, $this->object->getPosition());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Pointer::prevPosition
   */
  public function testPrevPosition(){
    $this->object->nextPosition();
    $this->object->prevPosition();
    $this->assertEquals(5, $this->object->getPosition());
  }
}
