<?php
namespace PPHP\tests\tools\classes\special\storage\relationTable;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-14 at 19:25:58.
 */
class StringFieldTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\special\storage\relationTable\StringField
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\StringField('test', 5);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::verify
   */
  public function testVerify(){
    $this->assertTrue($this->object->verify('12345'));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::verify
   */
  public function testVerifyIfBadSize(){
    $this->assertFalse($this->object->verify('123456'));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::verify
   */
  public function testVerifyIfNullGiven(){
    $this->assertTrue($this->object->verify());
    $this->assertTrue($this->object->verify(''));
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\StringField('test', 5, true);
    $this->assertFalse($this->object->verify());
    $this->assertFalse($this->object->verify(''));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::verify
   */
  public function testVerifyDefault(){
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\StringField('test', 5, false, '12345');
    $this->assertTrue($this->object->verify());
    $this->assertTrue($this->object->verify(''));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::verify
   */
  public function testVerifyIfNullGivenAndDefault(){
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\StringField('test', 5, true, '12345');
    $this->assertTrue($this->object->verify());
    $this->assertTrue($this->object->verify(''));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::serializeData
   */
  public function testSerializeData(){
    $this->assertEquals('  123', $this->object->serializeData('123'));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::serializeData
   */
  public function testSerializeDataDefault(){
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\StringField('test', 5, false, '12345');
    $this->assertEquals('12345', $this->object->serializeData(''));
    $this->assertEquals('12345', $this->object->serializeData());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::serializeData
   */
  public function testSerializeDataIfNullGiven(){
    $this->assertEquals('     ', $this->object->serializeData());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::unserializeData
   */
  public function testUnserializeData(){
    $this->assertEquals('123', $this->object->unserializeData('  123'));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\StringField::getSizeData
   */
  public function testGetSizeData(){
    $this->assertEquals(5, $this->object->getSizeData());
  }
}
