<?php
namespace PPHP\tests\tools\classes\special\storage\relationTable;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-16 at 19:20:33.
 */
class StructureTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\special\storage\relationTable\Structure
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\special\storage\relationTable\Structure();
    $this->object->addField(new TestField('field1'));
    $this->object->addField(new TestField('field2'));
    $this->object->addField(new TestField('field3'));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Structure::addField
   */
  public function testAddField(){
    $this->object->addField(new TestField('field4'));
    $this->assertEquals(4, $this->object->getCountFields());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Structure::getSizeData
   */
  public function testGetSizeData(){
    $this->assertEquals(3, $this->object->getSizeData());
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Structure::serializeData
   */
  public function testSerializeData(){
    $this->assertEquals('123', $this->object->serializeData(['field1' => 1, 'field2' => 2, 'field3' => 3]));
  }

  /**
   * @covers PPHP\tools\classes\special\storage\relationTable\Structure::unserializeData
   */
  public function testUnserializeData(){
    $this->assertEquals(['field1' => 1, 'field2' => 2, 'field3' => 3], $this->object->unserializeData('123'));
  }
}
