<?php
namespace PPHP\tests\tools\classes\standard\storage\database\queryCreator;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-07 at 07:44:46.
 */
class HierarchicalQueryCreatorTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\standard\storage\database\queryCreator\HierarchicalQueryCreator
   */
  protected $object;

  /**
   * Тестовый сервис автоинкрементации.
   * @var TestAutoinc
   */
  static protected $autoinc;

  public static function setUpBeforeClass(){
    self::$autoinc = TestAutoinc::getInstance();
  }

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\standard\storage\database\queryCreator\HierarchicalQueryCreator(self::$autoinc);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\storage\database\queryCreator\HierarchicalQueryCreator::createUpdateChildQuery
   */
  public function testCreateUpdateChildQuery(){
    $testObject = new \PPHP\tests\tools\classes\standard\essence\structures\hierarchical\MockHierarchicalEntity;
    $testObject->setOID(1);
    $this->assertEquals('UPDATE `MockHierarchicalEntity` SET `parent` = "NULL" WHERE (`parent` = "$/PPHP/tests/tools/classes/standard/essence/structures/hierarchical/MockHierarchicalEntity:1")', $this->object->createUpdateChildQuery($testObject)->interpretation());
  }

  /**
   * @covers PPHP\tools\classes\standard\storage\database\queryCreator\HierarchicalQueryCreator::createUpdateChildQuery
   */
  public function testCreateUpdateChildQueryIfParentExists(){
    $parentObject = new \PPHP\tests\tools\classes\standard\essence\structures\hierarchical\MockHierarchicalEntity;
    $parentObject->setOID(2);
    $testObject = new \PPHP\tests\tools\classes\standard\essence\structures\hierarchical\MockHierarchicalEntity;
    $testObject->setOID(1);
    $testObject->setHierarchicalParent($parentObject);
    $this->assertEquals('UPDATE `MockHierarchicalEntity` SET `parent` = "$/PPHP/tests/tools/classes/standard/essence/structures/hierarchical/MockHierarchicalEntity:2" WHERE (`parent` = "$/PPHP/tests/tools/classes/standard/essence/structures/hierarchical/MockHierarchicalEntity:1")', $this->object->createUpdateChildQuery($testObject)->interpretation());
  }

  public function testCreateAssociationSelectQuery(){
    $testObject = new \PPHP\tests\tools\classes\standard\essence\structures\hierarchical\MockHierarchicalEntity;
    $testObject->setOID(1);
    $this->assertEquals('SELECT `prop` as prop,`parent` as hierarchicalParent,`OID` as OID FROM `MockHierarchicalEntity`  WHERE (`OID` = "$/PPHP/tests/tools/classes/standard/essence/structures/hierarchical/MockHierarchicalEntity:1")', $this->object->createAssociationSelectQuery($testObject, $testObject->getReflectionProperty('hierarchicalChild'))->interpretation());
  }
}
