<?php
namespace PPHP\tests\tools\classes\standard\baseType\special\people;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-21 at 18:47:47.
 */
class PhoneNumberTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\standard\baseType\special\people\PhoneNumber
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\standard\baseType\special\people\PhoneNumber('+1(234)5678901');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is
   */
  public function testIs(){
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is(''));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('+0(0)0'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('+9(99999)999999999'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('0(123)4567890'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('+0123456789'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('+0(123)'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('(123)456789'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('123'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::is('abc'));
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::getCode
   */
  public function testGetCode(){
    $this->assertEquals('234', $this->object->getCode());
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::getNumber
   */
  public function testGetNumber(){
    $this->assertEquals('5678901', $this->object->getNumber());
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\people\PhoneNumber::getRegion
   */
  public function testGetRegion(){
    $this->assertEquals('1', $this->object->getRegion());
  }
}
