<?php
namespace PPHP\tests\services\formatting\localisation;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-06 at 18:34:22.
 */
class TestLocaliseClassTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\services\formatting\localisation\LocalisationManager
   */
  protected $object;


  /**
   * @var \PPHP\tests\services\formatting\localisation\TestLocaliseClass
   */
  protected $localiseClass;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = \PPHP\services\formatting\localisation\LocalisationManager::getInstance();
    $this->localiseClass = new TestLocaliseClass();
    $this->object->setLocalise(\PPHP\services\formatting\localisation\LocalisationManager::RUSSIA);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers \PPHP\services\formatting\localisation\LocalisationManager::localiseClass
   */
  public function testLocaliseClass(){
    $this->assertEquals('Тестовый класс', $this->object->localiseClass($this->localiseClass->getReflectionClass()));
  }

  /**
   * @covers \PPHP\services\formatting\localisation\LocalisationManager::localiseProperty
   */
  public function testLocaliseProperty(){
    $this->assertEquals('Сообщение', $this->object->localiseProperty($this->localiseClass->getReflectionClass(), $this->localiseClass->getReflectionProperty('message')));
  }

  /**
   * @covers \PPHP\services\formatting\localisation\LocalisationManager::localiseProperty
   */
  public function testLocaliseMessage(){
    $this->assertEquals('Другие локализованные данные', $this->object->localiseMessage($this->localiseClass->getReflectionClass(), 'OtherData'));
  }
}
