<?php
namespace PPHP\tests\tools\classes\standard\baseType;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-10 at 08:56:01.
 */
class FloatTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\standard\baseType\Float
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new \PPHP\tools\classes\standard\baseType\Float(1.2345);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\Float::is
   */
  public function testIs(){
    $this->assertTrue($this->object->is(10));
    $this->assertTrue($this->object->is(-10));
    $this->assertTrue($this->object->is(1.0));
    $this->assertTrue($this->object->is(-1.0));
    $this->assertTrue($this->object->is(1.5));
    $this->assertTrue($this->object->is(-1.5));
    $this->assertTrue($this->object->is(true));
    $this->assertTrue($this->object->is(false));
    $this->assertTrue($this->object->is('5'));
    $this->assertTrue($this->object->is('-5'));
    $this->assertTrue($this->object->is('1.0'));
    $this->assertTrue($this->object->is('-1.0'));
    $this->assertTrue($this->object->is('1.5'));
    $this->assertTrue($this->object->is('-1.5'));
    $this->assertFalse($this->object->is('5a'));
    $this->assertFalse($this->object->is('1.0a'));
    $this->assertFalse($this->object->is('1.5a'));
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\Float::verify
   */
  public function testVerify(){
    $this->assertTrue($this->object->verify());
    $this->assertTrue($this->object->verify(0));
    $this->assertFalse($this->object->verify(2));
    $this->assertTrue($this->object->verify(null, 2));
    $this->assertFalse($this->object->verify(null, 1));
    $this->assertTrue($this->object->verify(0, 2));
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\Float::prevent
   */
  public function testPrevent(){
    $this->assertEquals(1.2345, $this->object->prevent(0, 2)->getVal());
    $this->assertEquals(2.0, $this->object->prevent(2)->getVal());
    $this->assertEquals(1.0, $this->object->prevent(null, 1)->getVal());
  }
}
