<?php
namespace PPHP\tests\tools\classes\standard\baseType\special;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-13 at 20:04:40.
 */
class AliasTest extends \PHPUnit_Framework_TestCase{
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\Alias::is
   */
  public function testIs(){
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\Alias::is(''));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\Alias::is('a1 b'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\Alias::is('_-?*-/!@#'));
  }
}
