<?php
namespace PPHP\tests\tools\classes\standard\baseType\special;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-11 at 15:30:26.
 */
class NameTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\standard\baseType\special\Name
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\Name::is
   */
  public function testIs(){
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\Name::is(''));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\Name::is('a'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\Name::is('_a'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\Name::is('a_b'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\Name::is('a1'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\Name::is('1a'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\Name::is('_1'));
  }
}
