<?php
namespace PPHP\tests\services\database\identification;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-11 at 06:44:41.
 */
class AutoincrementTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\services\database\identification\Autoincrement
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = \PPHP\services\database\identification\Autoincrement::getInstance();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
    $this->object->resetOID();
  }

  /**
   * @covers \PPHP\services\database\identification\Autoincrement::generateOID
   */
  public function testGenerateOID(){
    $this->assertEquals(1, $this->object->generateOID());
    $this->assertEquals(2, $this->object->generateOID());
  }

  /**
   * @covers \PPHP\services\database\identification\Autoincrement::resetOID
   */
  public function testResetOID(){
    $this->assertEquals(1, $this->object->generateOID());
    $this->object->resetOID();
    $this->assertEquals(1, $this->object->generateOID());
  }
}
