<?php
namespace PPHP\tests\tools\patterns\database;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-21 at 09:24:22.
 */
class OIDTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var TestLongObject
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->object = new TestLongObject;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\patterns\database\identification\TOID::setOID
   * @covers PPHP\tools\patterns\database\identification\TOID::getOID
   */
  public function testSetOID(){
    $this->object->setOID(1);
    $this->assertEquals(1, $this->object->getOID());
  }

  /**
   * @covers PPHP\tools\patterns\database\identification\TOID::isOID
   */
  public function testIsOID(){
    $this->assertFalse($this->object->isOID());
    $this->object->setOID(1);
    $this->assertTrue($this->object->isOID());
  }

  /**
   * @covers PPHP\tools\patterns\database\identification\TOID::getProxy
   */
  public function testGetProxy(){
    $object = TestLongObject::getProxy(1);
    $this->assertTrue($object->isOID());
    $this->assertEquals(1, $object->getOID());
  }

  /**
   * @covers PPHP\tools\patterns\database\identification\TOID::getLinkOID
   */
  public function testGetLinkOID(){
    $object = TestLongObject::getProxy(1);
    $this->assertEquals('$/PPHP/tests/tools/patterns/database/TestLongObject:1', $object->getLinkOID());
  }
}
