<?php
namespace PPHP\tests\tools\patterns\memento;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-20 at 18:26:28.
 */
class MementoTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\patterns\memento\Memento
   */
  protected $memento;

  /**
   * @var TestOriginator
   */
  protected $originator;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
    $this->originator = new TestOriginator();
    $this->memento = $this->originator->createMemento();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\patterns\memento\TOriginator::createMemento
   * @covers PPHP\tools\patterns\memento\Memento::__construct
   */
  public function testCreateMemento(){
    $this->assertInstanceOf('\PPHP\tools\patterns\memento\Memento', $this->originator->createMemento());
  }

  /**
   * @covers PPHP\tools\patterns\memento\TOriginator::restoreFromMemento
   */
  public function testRestoreFromMemento(){
    $this->originator->setTestVar(3);
    $this->originator->restoreFromMemento($this->memento);
    $this->assertEquals(5, $this->originator->getTestVar());
  }

  /**
   * @covers PPHP\tools\patterns\memento\Memento::getState
   */
  public function testGetState(){
    $this->assertEquals(['testVar' => 5], $this->memento->getState($this->originator));
  }

  /**
   * @covers PPHP\tools\patterns\memento\Memento::getState
   */
  public function testGetStateIfNonOwner(){
    $this->setExpectedException('\PPHP\tools\patterns\memento\AccessException');
    $this->memento->getState(new TestOriginator());
  }
}
