<?php
namespace PPHP\tests\tools\classes\standard\baseType\special\network;

spl_autoload_register(function($className){
  require_once $_SERVER['DOCUMENT_ROOT'] . '/' . str_replace('\\', '/', $className) . '.php';
});
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-13 at 08:29:45.
 */
class PortTest extends \PHPUnit_Framework_TestCase{
  /**
   * @var \PPHP\tools\classes\standard\baseType\special\network\Port
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(){
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(){
  }

  /**
   * @covers PPHP\tools\classes\standard\baseType\special\network\Port::is
   */
  public function testIs(){
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\network\Port::is(''));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\network\Port::is('0'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\network\Port::is(0));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\network\Port::is('65536'));
    $this->assertTrue(\PPHP\tools\classes\standard\baseType\special\network\Port::is(65536));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\network\Port::is('-1'));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\network\Port::is(-1));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\network\Port::is(65537));
    $this->assertFalse(\PPHP\tools\classes\standard\baseType\special\network\Port::is('a'));
  }
}
